In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub

# Download latest version
path = kagglehub.competition_download('playground-series-s6e9')

print("Path to competition files:", path)
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/playground-series-s6e9/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e9/train.csv
/kaggle/input/competitions/playground-series-s6e9/test.csv
Path to competition files: /kaggle/input/competitions/playground-series-s6e9

In [2]:
train= pd.read_csv("/kaggle/input/competitions/playground-series-s6e9/train.csv")
test= pd.read_csv("/kaggle/input/competitions/playground-series-s6e9/test.csv")
train.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

In [3]:
test.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level
0,668665,61,67725.0,16.9,2,7,4,4.0,Male,Suburban,Sedan,Yes,No,Low
1,668666,42,152835.0,41.9,2,9,9,4.0,Male,Urban,SUV,No,No,Low
2,668667,68,86877.0,53.3,1,10,11,4.0,Female,Urban,Sedan,No,No,Low
3,668668,39,46794.0,34.1,2,4,8,4.0,Female,Suburban,Sedan,Yes,No,Low
4,668669,55,112172.0,57.2,1,6,4,1.0,Female,Suburban,Sedan,Yes,Yes,Low

train.drop(columns="id")
test.drop(columns="id")

## Missing Values

In [5]:
train.isnull().mean()*100

id                             0.0
Age                            0.0
Annual_Income_USD              0.0
Daily_Commute_km               0.0
Number_of_Cars_Owned           0.0
Charging_Stations_Near_Home    0.0
Charging_Stations_Near_Work    0.0
Environmental_Concern_Level    0.0
Gender                         0.0
City_Type                      0.0
Current_Car_Type               0.0
Home_Charging_Possible         0.0
Subsidy_Available              0.0
Range_Anxiety_Level            0.0
Will_Buy_EV                    0.0
dtype: float64

In [6]:
test.isnull().mean()*100

id                             0.0
Age                            0.0
Annual_Income_USD              0.0
Daily_Commute_km               0.0
Number_of_Cars_Owned           0.0
Charging_Stations_Near_Home    0.0
Charging_Stations_Near_Work    0.0
Environmental_Concern_Level    0.0
Gender                         0.0
City_Type                      0.0
Current_Car_Type               0.0
Home_Charging_Possible         0.0
Subsidy_Available              0.0
Range_Anxiety_Level            0.0
dtype: float64

## Encoding

In [7]:
train["Gender"].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [9]:
print(train["Number_of_Cars_Owned"].unique())
print(train["Environmental_Concern_Level"].unique())
print(train["Charging_Stations_Near_Home"].unique())
print(train["Charging_Stations_Near_Work"].unique())
print(train["City_Type"].unique())
print(train["Current_Car_Type"].unique())

[2 1 4 3]
[1. 4. 5. 3. 2.]
[ 3  2  8  6  1 13 11  0  9  7 10  4  5 14 12]
[ 7  2 15  9  3  5  1 17 18 11 16 12 14 13 10  0  8 19  4  6]
['Suburban' 'Rural' 'Urban']
['Sedan' 'SUV' 'Hatchback' 'Truck']