In [16]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub

# Download latest version
path = kagglehub.competition_download('playground-series-s6e9')

print("Path to competition files:", path)
# kagglehub.dataset_download('<owner>/<dataset-slug>')

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.
/kaggle/input/competitions/playground-series-s6e9/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e9/train.csv
/kaggle/input/competitions/playground-series-s6e9/test.csv
Path to competition files: /kaggle/input/competitions/playground-series-s6e9

In [17]:
train= pd.read_csv("/kaggle/input/competitions/playground-series-s6e9/train.csv")
test= pd.read_csv("/kaggle/input/competitions/playground-series-s6e9/test.csv")
train.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

In [18]:
test.head()

,id,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level
0,668665,61,67725.0,16.9,2,7,4,4.0,Male,Suburban,Sedan,Yes,No,Low
1,668666,42,152835.0,41.9,2,9,9,4.0,Male,Urban,SUV,No,No,Low
2,668667,68,86877.0,53.3,1,10,11,4.0,Female,Urban,Sedan,No,No,Low
3,668668,39,46794.0,34.1,2,4,8,4.0,Female,Suburban,Sedan,Yes,No,Low
4,668669,55,112172.0,57.2,1,6,4,1.0,Female,Suburban,Sedan,Yes,Yes,Low

In [19]:
train= train.drop(columns="id")
test= test.drop(columns="id")
train.head()

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Gender,City_Type,Current_Car_Type,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Will_Buy_EV
0,66,92887.0,23.4,2,3,7,1.0,Male,Suburban,Sedan,Yes,No,Low,No
1,38,30000.0,5.0,1,2,2,4.0,Male,Rural,SUV,Yes,No,Low,No
2,26,94389.0,36.8,1,8,15,5.0,Female,Urban,Sedan,No,Yes,Low,Yes
3,66,73580.0,23.7,2,6,9,3.0,Male,Suburban,Hatchback,Yes,No,Low,No
4,54,57898.0,50.8,1,2,3,3.0,Male,Suburban,Hatchback,Yes,No,Low,No

## Missing Values

In [20]:
train.isnull().mean()*100

Age                            0.0
Annual_Income_USD              0.0
Daily_Commute_km               0.0
Number_of_Cars_Owned           0.0
Charging_Stations_Near_Home    0.0
Charging_Stations_Near_Work    0.0
Environmental_Concern_Level    0.0
Gender                         0.0
City_Type                      0.0
Current_Car_Type               0.0
Home_Charging_Possible         0.0
Subsidy_Available              0.0
Range_Anxiety_Level            0.0
Will_Buy_EV                    0.0
dtype: float64

In [21]:
test.isnull().mean()*100

Age                            0.0
Annual_Income_USD              0.0
Daily_Commute_km               0.0
Number_of_Cars_Owned           0.0
Charging_Stations_Near_Home    0.0
Charging_Stations_Near_Work    0.0
Environmental_Concern_Level    0.0
Gender                         0.0
City_Type                      0.0
Current_Car_Type               0.0
Home_Charging_Possible         0.0
Subsidy_Available              0.0
Range_Anxiety_Level            0.0
dtype: float64

## Encoding

In [22]:
train["Gender"].unique()

array(['Male', 'Female', 'Other'], dtype=object)

In [23]:
print(train["Number_of_Cars_Owned"].unique())
print(train["Environmental_Concern_Level"].unique())
print(train["Charging_Stations_Near_Home"].unique())
print(train["Charging_Stations_Near_Work"].unique())
print(train["City_Type"].unique())
print(train["Current_Car_Type"].unique())

[2 1 4 3]
[1. 4. 5. 3. 2.]
[ 3  2  8  6  1 13 11  0  9  7 10  4  5 14 12]
[ 7  2 15  9  3  5  1 17 18 11 16 12 14 13 10  0  8 19  4  6]
['Suburban' 'Rural' 'Urban']
['Sedan' 'SUV' 'Hatchback' 'Truck']

In [24]:
## Using OneHotEncoder for Gender, City_Type and Current_Car_Type
train = pd.get_dummies(train, columns=["Gender","City_Type","Current_Car_Type"], prefix=["Gender","City_Type","Current_Car_Type"], dtype=int)

In [25]:
train

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,...,Gender_Female,Gender_Male,Gender_Other,City_Type_Rural,City_Type_Suburban,City_Type_Urban,Current_Car_Type_Hatchback,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck
0,66,92887.0,23.4,2,3,7,1.0,Yes,No,Low,...,0,1,0,0,1,0,0,0,1,0
1,38,30000.0,5.0,1,2,2,4.0,Yes,No,Low,...,0,1,0,1,0,0,0,1,0,0
2,26,94389.0,36.8,1,8,15,5.0,No,Yes,Low,...,1,0,0,0,0,1,0,0,1,0
3,66,73580.0,23.7,2,6,9,3.0,Yes,No,Low,...,0,1,0,0,1,0,1,0,0,0
4,54,57898.0,50.8,1,2,3,3.0,Yes,No,Low,...,0,1,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,30,71090.0,27.4,2,5,6,5.0,No,Yes,Medium,...,0,1,0,0,0,1,0,0,1,0
668661,32,129990.0,5.0,2,5,4,1.0,Yes,Yes,Low,...,1,0,0,0,1,0,0,1,0,0
668662,64,121791.0,24.2,1,5,6,1.0,Yes,Yes,Low,...,1,0,0,0,1,0,1,0,0,0
668663,51,115923.0,43.7,2,0,0,1.0,Yes,Yes,Low,...,1,0,0,1,0,0,0,1,0,0
668664,54,68986.0,5.0,1,6,9,2.0,No,Yes,Low,...,0,1,0,0,0,1,1,0,0,0

In [26]:
## Using Ordinal Encoder for Home_Charging_Possible,Subsidy_Available	and Range_Anxiety_Level
cat=["No","Yes"]
from sklearn.preprocessing import OrdinalEncoder
enc= OrdinalEncoder(categories=[cat])
train["Home_Charging_Possible"]= enc.fit_transform(train[["Home_Charging_Possible"]])
train["Subsidy_Available"]= enc.fit_transform(train[["Subsidy_Available"]])
train

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,...,Gender_Female,Gender_Male,Gender_Other,City_Type_Rural,City_Type_Suburban,City_Type_Urban,Current_Car_Type_Hatchback,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck
0,66,92887.0,23.4,2,3,7,1.0,1.0,0.0,Low,...,0,1,0,0,1,0,0,0,1,0
1,38,30000.0,5.0,1,2,2,4.0,1.0,0.0,Low,...,0,1,0,1,0,0,0,1,0,0
2,26,94389.0,36.8,1,8,15,5.0,0.0,1.0,Low,...,1,0,0,0,0,1,0,0,1,0
3,66,73580.0,23.7,2,6,9,3.0,1.0,0.0,Low,...,0,1,0,0,1,0,1,0,0,0
4,54,57898.0,50.8,1,2,3,3.0,1.0,0.0,Low,...,0,1,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,30,71090.0,27.4,2,5,6,5.0,0.0,1.0,Medium,...,0,1,0,0,0,1,0,0,1,0
668661,32,129990.0,5.0,2,5,4,1.0,1.0,1.0,Low,...,1,0,0,0,1,0,0,1,0,0
668662,64,121791.0,24.2,1,5,6,1.0,1.0,1.0,Low,...,1,0,0,0,1,0,1,0,0,0
668663,51,115923.0,43.7,2,0,0,1.0,1.0,1.0,Low,...,1,0,0,1,0,0,0,1,0,0
668664,54,68986.0,5.0,1,6,9,2.0,0.0,1.0,Low,...,0,1,0,0,0,1,1,0,0,0

In [27]:
cat=["Low","Medium","High"]
enc= OrdinalEncoder(categories=[cat])
train["Range_Anxiety_Level"]= enc.fit_transform(train[["Range_Anxiety_Level"]])
train

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,...,Gender_Female,Gender_Male,Gender_Other,City_Type_Rural,City_Type_Suburban,City_Type_Urban,Current_Car_Type_Hatchback,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck
0,66,92887.0,23.4,2,3,7,1.0,1.0,0.0,0.0,...,0,1,0,0,1,0,0,0,1,0
1,38,30000.0,5.0,1,2,2,4.0,1.0,0.0,0.0,...,0,1,0,1,0,0,0,1,0,0
2,26,94389.0,36.8,1,8,15,5.0,0.0,1.0,0.0,...,1,0,0,0,0,1,0,0,1,0
3,66,73580.0,23.7,2,6,9,3.0,1.0,0.0,0.0,...,0,1,0,0,1,0,1,0,0,0
4,54,57898.0,50.8,1,2,3,3.0,1.0,0.0,0.0,...,0,1,0,0,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668660,30,71090.0,27.4,2,5,6,5.0,0.0,1.0,1.0,...,0,1,0,0,0,1,0,0,1,0
668661,32,129990.0,5.0,2,5,4,1.0,1.0,1.0,0.0,...,1,0,0,0,1,0,0,1,0,0
668662,64,121791.0,24.2,1,5,6,1.0,1.0,1.0,0.0,...,1,0,0,0,1,0,1,0,0,0
668663,51,115923.0,43.7,2,0,0,1.0,1.0,1.0,0.0,...,1,0,0,1,0,0,0,1,0,0
668664,54,68986.0,5.0,1,6,9,2.0,0.0,1.0,0.0,...,0,1,0,0,0,1,1,0,0,0

In [29]:
## Encoding for test data
## Using OneHotEncoder for Gender, City_Type and Current_Car_Type
test = pd.get_dummies(test, columns=["Gender","City_Type","Current_Car_Type"], prefix=["Gender","City_Type","Current_Car_Type"], dtype=int)
## Using Ordinal Encoder for Home_Charging_Possible,Subsidy_Available	and Range_Anxiety_Level
cat=["No","Yes"]
from sklearn.preprocessing import OrdinalEncoder
enc= OrdinalEncoder(categories=[cat])
test["Home_Charging_Possible"]= enc.fit_transform(test[["Home_Charging_Possible"]])
test["Subsidy_Available"]= enc.fit_transform(test[["Subsidy_Available"]])
cat=["Low","Medium","High"]
enc= OrdinalEncoder(categories=[cat])
test["Range_Anxiety_Level"]= enc.fit_transform(test[["Range_Anxiety_Level"]])
test

,Age,Annual_Income_USD,Daily_Commute_km,Number_of_Cars_Owned,Charging_Stations_Near_Home,Charging_Stations_Near_Work,Environmental_Concern_Level,Home_Charging_Possible,Subsidy_Available,Range_Anxiety_Level,Gender_Female,Gender_Male,Gender_Other,City_Type_Rural,City_Type_Suburban,City_Type_Urban,Current_Car_Type_Hatchback,Current_Car_Type_SUV,Current_Car_Type_Sedan,Current_Car_Type_Truck
0,61,67725.0,16.9,2,7,4,4.0,1.0,0.0,0.0,0,1,0,0,1,0,0,0,1,0
1,42,152835.0,41.9,2,9,9,4.0,0.0,0.0,0.0,0,1,0,0,0,1,0,1,0,0
2,68,86877.0,53.3,1,10,11,4.0,0.0,0.0,0.0,1,0,0,0,0,1,0,0,1,0
3,39,46794.0,34.1,2,4,8,4.0,1.0,0.0,0.0,1,0,0,0,1,0,0,0,1,0
4,55,112172.0,57.2,1,6,4,1.0,1.0,1.0,0.0,1,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286566,63,75830.0,23.9,1,3,3,1.0,1.0,0.0,0.0,0,1,0,0,1,0,0,1,0,0
286567,27,79563.0,55.2,2,7,5,3.0,1.0,1.0,0.0,0,1,0,0,1,0,0,0,1,0
286568,30,48183.0,42.6,3,7,7,4.0,1.0,0.0,0.0,1,0,0,0,1,0,0,0,1,0
286569,32,107845.0,5.0,2,14,7,1.0,0.0,0.0,0.0,1,0,0,0,0,1,0,1,0,0
286570,42,64626.0,5.0,1,7,7,1.0,1.0,0.0,0.0,1,0,0,0,1,0,0,1,0,0